In [1]:
# Path to user functions
import sys
sys.path.append("../Src/")
# display Python Version
from platform import python_version
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
# user functions
import utilities as u
import statistical_testing as st
import plot_function as pf

# ML libraries
import xgboost as xgb
import lightgbm as lgb

# Initialize variables
RANDOM_STATE = 1776

# print versions
print("Numpy Version: " + np.__version__)
print("Pandas Version: " + pd.__version__)
print("Seaborn Version: " + sns.__version__)
print("Matplotlib Version: " + plt.matplotlib.__version__)
print("Python Version: " + python_version())
print("XGBoost Version: " + xgb.__version__)
print("Lightgbm Version: " + lgb.__version__)

Numpy Version: 2.1.2
Pandas Version: 2.3.1
Seaborn Version: 0.13.2
Matplotlib Version: 3.10.5
Python Version: 3.13.5
XGBoost Version: 3.0.3
Lightgbm Version: 4.6.0

## Load Datasets

In [9]:
# load data
df_train = pd.read_pickle('../Data/df_train_processed.pkl')
df_test = pd.read_pickle('../Data/df_test_processed.pkl')

In [10]:
df_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,trans_day_of_week_cos,age,industry,cc_network,store_distance,amt_log,age_group,city_fraud_rate,city_fraud_count,city_total_transactions
0,0,2019-01-01 00:00:18,2703186189652095,"Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,0.62349,37,Airlines & Financial,Mastercard,48.838332,1.786747,Age Group(36-44),0.000000,0,2028
1,1,2019-01-01 00:00:44,630423337322,"Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,0.62349,47,"Merchandising & Banking (e.g., Discover)",Maestro,18.773001,4.684259,Age Group(44-53),0.000000,0,3545
2,2,2019-01-01 00:00:51,38859492057661,Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,0.62349,63,"Travel & Entertainment (e.g., American Express...",Diners Club,67.236235,5.398660,Age Group(53-66),0.000000,0,503
3,3,2019-01-01 00:01:16,3534093764340240,"Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,0.62349,58,"Travel & Entertainment (e.g., American Express...",JCB,59.448671,3.828641,Age Group(53-66),0.030426,15,493
4,4,2019-01-01 00:03:06,375534208663984,Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,0.62349,39,"Travel & Entertainment (e.g., American Express...",American Express,48.191592,3.760269,Age Group(36-44),0.000000,0,2017

In [11]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 45 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Unnamed: 0               1296675 non-null  int64
 1   trans_date_trans_time    1296675 non-null  datetime64[ns]
 2   cc_num                   1296675 non-null  int64
 3   merchant                 1296675 non-null  category
 4   category                 1296675 non-null  category
 5   amt                      1296675 non-null  float64
 6   first                    1296675 non-null  object
 7   last                     1296675 non-null  object
 8   gender                   1296675 non-null  category
 9   street                   1296675 non-null  object
 10  city                     1296675 non-null  category
 11  state                    1296675 non-null  category
 12  zip                      1296675 non-null  category
 13  lat                      1296675 non-null  float64
 14  long                     1296675 non-null  float64
 15  city_pop                 1296675 non-null  int64
 16  job                      1296675 non-null  category
 17  dob                      1296675 non-null  datetime64[ns]
 18  trans_num                1296675 non-null  object
 19  unix_time                1296675 non-null  int64
 20  merch_lat                1296675 non-null  float64
 21  merch_long               1296675 non-null  float64
 22  is_fraud                 1296675 non-null  int64
 23  trans_qtr                1296675 non-null  category
 24  trans_month              1296675 non-null  category
 25  trans_day                1296675 non-null  category
 26  trans_day_of_week        1296675 non-null  category
 27  trans_hour               1296675 non-null  category
 28  trans_week_of_year       1296675 non-null  category
 29  is_weekend               1296675 non-null  bool
 30  trans_hour_sin           1296675 non-null  float64
 31  trans_hour_cos           1296675 non-null  float64
 32  trans_month_sin          1296675 non-null  float64
 33  trans_month_cos          1296675 non-null  float64
 34  trans_day_of_week_sin    1296675 non-null  float64
 35  trans_day_of_week_cos    1296675 non-null  float64
 36  age                      1296675 non-null  int64
 37  industry                 1296675 non-null  category
 38  cc_network               1296675 non-null  category
 39  store_distance           1296675 non-null  float64
 40  amt_log                  1296675 non-null  float64
 41  age_group                1296675 non-null  category
 42  city_fraud_rate          1296675 non-null  float64
 43  city_fraud_count         1296675 non-null  int64
 44  city_total_transactions  1296675 non-null  int64
dtypes: bool(1), category(16), datetime64[ns](2), float64(14), int64(8), object(4)
memory usage: 303.0+ MB